language: scala

matrix:
  include:
  - scala: 2.12.3
    jdk: oraclejdk8
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/boot/"

script:
- sbt ++$TRAVIS_SCALA_VERSION scalafmtCheckAll scalastyle compile 
- sbt ++$TRAVIS_SCALA_VERSION coverage test coverageReport
