addSbtPlugin("org.scalastyle"     %% "scalastyle-sbt-plugin" % "1.0.0")
addSbtPlugin("org.scalameta"      % "sbt-scalafmt"           % "2.0.3")
addSbtPlugin("org.scoverage"      % "sbt-scoverage"          % "1.5.1")
addSbtPlugin("com.github.gseitz"  % "sbt-release"            % "1.0.11")
addSbtPlugin("com.frugalmechanic" % "fm-sbt-s3-resolver"     % "0.18.0")
