addSbtPlugin("org.scalastyle"     %% "scalastyle-sbt-plugin" % "1.0.0")
addSbtPlugin("org.scalameta"      % "sbt-scalafmt"           % "2.4.3")
addSbtPlugin("org.scoverage"      % "sbt-scoverage"          % "1.7.3")
addSbtPlugin("com.github.gseitz"  % "sbt-release"            % "1.0.13")
addSbtPlugin("com.frugalmechanic" % "fm-sbt-s3-resolver"     % "0.19.0")
